korrigiert:
  text: |
    {{REDaten
    |KORREKTURSTAND=korrigiert
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 2
    - []

fertig:
  text: |
    {{REDaten
    |KORREKTURSTAND=Fertig
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 3
    - []

unkorrigiert:
  text: |
    {{REDaten
    |KORREKTURSTAND=Unkorrigiert
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 1
    - []

not_valid:
  text: |
    {{REDaten
    |KORREKTURSTAND=bla
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 0
    - []

not_gemeinfrei:
  text: |
    {{REDaten
    |KORREKTURSTAND=korrigiert
    |TODESJAHR=9999
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 0
    - []
platzhalter:
  text: |
    {{REDaten
    |KORREKTURSTAND=Platzhalter
    |TODESJAHR=9999
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 0
    - []
unvollständig:
  text: |
    {{REDaten
    |KORREKTURSTAND=Unvollständig
    |TODESJAHR=9999
    }}
    text.
    {{REAutor|OFF}}
  result:
    - proof_read: 0
    - []